# ==========================
# Configuraciones generales
# ==========================
spring.application.name=Dev-Sistema-de-ventas-supermercado
server.port=8090

# ==========================
# Configuraciones de MySQL
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====================================
# Configuraciones de JPA y Hibernate
# ====================================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ============================
# Spring Boot Actuator Config
# ============================
info.app.name=Sistema de ventas
#info.app.description
info.app.version=1.0.0
info.app.environment=Development

management.endpoints.web.exposure.include=*

# ============================
# Spring Security Config
# ============================
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG